Frank/new dev env (#26)
* ci: support for dev envs

* ci: environment fix

* ci: env fix

* ci: unique branch name

* ci: ecr login

* ci: envcli support:

* chore: double quotes

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -68,11 +68,11 @@ jobs:
       - install_node_modules
       - setup_test_env
       - run:
-          name: 'Build package'
+          name: "Build package"
           command: |
             yarn build
       - run:
-          name: 'Run tests'
+          name: "Run tests"
           command: |
             yarn test
       - codecov/upload:
@@ -86,13 +86,16 @@ jobs:
 
   build-push-image:
     executor: build-executor
+    environment:
+      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/google"
     steps:
       - checkout # special step to check out source code to working directory
       - setup_remote_docker
       - run:
-          name: 'Build docker image'
+          name: "Build docker image"
           command: |
-            mkdir -p /tmp/vf-build/vars
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
             # Fix semantic versioning 
             if [ "$CIRCLE_BRANCH" == "master" ]; then
               npm config set unsafe-perm true # needed for npx to work
@@ -115,34 +118,80 @@ jobs:
               --build-arg build_BUILD_URL=${CIRCLE_BUILD_URL}	\
               --build-arg build_GIT_SHA=${CIRCLE_SHA1} \
               --build-arg build_SEM_VER=${SEM_VER} \
-              -t 168387678261.dkr.ecr.us-east-1.amazonaws.com/google:k8s-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM . 
-            echo $CIRCLE_BUILD_NUM > /tmp/vf-build/vars/build_num
+              -t $IMAGE_NAME .
       - run:
-          name: 'Push docker images'
+          name: "Push docker images"
           command: |
-            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/google:k8s-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM
-            docker tag 168387678261.dkr.ecr.us-east-1.amazonaws.com/google:k8s-$CIRCLE_BRANCH-$CIRCLE_BUILD_NUM 168387678261.dkr.ecr.us-east-1.amazonaws.com/google:latest-$CIRCLE_BRANCH
-            docker push 168387678261.dkr.ecr.us-east-1.amazonaws.com/google:latest-$CIRCLE_BRANCH
-      - persist_to_workspace:
-          root: vars
-          paths:
-            - build_num
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
+            docker push $IMAGE_NAME
+            docker tag $IMAGE_NAME $IMAGE_REPO:latest-$CIRCLE_BRANCH
+            docker push $IMAGE_REPO:latest-$CIRCLE_BRANCH
 
   deploy-image:
     executor: build-executor
+    environment:
+      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/google"
     steps:
-      - attach_workspace:
-          at: /tmp/vf-build/vars
       - run:
           name: Update kubernetes image
           command: |
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
             aws eks --region us-east-1 update-kubeconfig --name development
-            BUILD_NUM=$(cat /tmp/vf-build/vars/build_num)
-            kubectl set image --namespace voiceflow-v1 deployment/google-$CIRCLE_BRANCH app=168387678261.dkr.ecr.us-east-1.amazonaws.com/google:k8s-$CIRCLE_BRANCH-$BUILD_NUM
+            kubectl set image --namespace voiceflow-v1 deployment/google-$CIRCLE_BRANCH app=$IMAGE_NAME
             if [ "$CIRCLE_BRANCH" == "master" ]; then
               aws eks --region us-east-1 update-kubeconfig --name production
-              kubectl set image --namespace voiceflow-v1 deployment/google-production app=168387678261.dkr.ecr.us-east-1.amazonaws.com/google:k8s-$CIRCLE_BRANCH-$BUILD_NUM
+              kubectl set image --namespace voiceflow-v1 deployment/google-production app=$IMAGE_NAME
             fi
+
+  build-deploy-dev-env:
+    executor: build-executor
+    environment:
+      IMAGE_REPO: "168387678261.dkr.ecr.us-east-1.amazonaws.com/google"
+    steps:
+      - checkout # special step to check out source code to working directory
+      - setup_remote_docker # Need this to run DinD
+      - add_ssh_keys: # To enable write access to repository for removing development environment branches
+          fingerprints:
+            - "0d:70:64:7b:cf:1e:f2:63:ed:a0:98:3d:a9:e2:35:b9"
+      - run:
+          name: "Build dev environment image"
+          command: |
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
+            SEM_VER="$CIRCLE_BRANCH-$CIRCLE_SHA1"
+            $(aws ecr get-login --no-include-email --region us-east-1)
+            set +e
+            DOCKER_CLI_EXPERIMENTAL=enabled docker manifest inspect $IMAGE_NAME > /dev/null 2>&1
+            SEARCH_IMAGE_RESULT=$?
+            set -e
+            if [[ $SEARCH_IMAGE_RESULT -ne 0 ]]; then   # Only build the image if there are no existing images 
+              docker build \
+                --build-arg NPM_TOKEN=//registry.npmjs.org/:_authToken=${NPM_TOKEN} \
+                --build-arg build_BUILD_NUM=${CIRCLE_BUILD_NUM} \
+                --build-arg build_BUILD_URL=${CIRCLE_BUILD_URL}	\
+                --build-arg build_GIT_SHA=${CIRCLE_SHA1} \
+                --build-arg build_SEM_VER=${SEM_VER} \
+                -t $IMAGE_NAME . 
+              docker push $IMAGE_NAME
+            fi
+            git push origin --delete $CIRCLE_BRANCH --no-verify # Clean up git branch
+      - run:
+          name: Install latest envcli utility
+          command: |
+            API_URL="https://$GITHUB_TOKEN:@api.github.com/repos/voiceflow/envcli"
+            ASSET_ID=$(curl $API_URL/releases/latest | jq -r '.assets[2].id')
+            curl -J -L -H "Accept: application/octet-stream" "$API_URL/releases/assets/$ASSET_ID" --output envcli.tar.gz
+            tar -xf envcli.tar.gz
+      - run:
+          name: "Deploy dev environment image"
+          command: |
+            IMAGE_TAG="k8s-$CIRCLE_SHA1"
+            IMAGE_NAME="$IMAGE_REPO:$IMAGE_TAG"
+            ENV_NAME="${CIRCLE_BRANCH%%_*}"
+            aws eks --region us-east-1 update-kubeconfig --name development
+            NON_INTERACTIVE=true ./envcli edit component google google -n $ENV_NAME -i $IMAGE_NAME
 
   release:
     executor: default-executor
@@ -152,21 +201,48 @@ jobs:
 
 # When should each job run and what are their dependencies?
 workflows:
-  build-deploy:
+  build-deploy-staging:
+    jobs:
+      - build-push-image:
+          context: dev-test
+          filters:
+            branches:
+              only:
+                - staging
+      - deploy-image:
+          context: dev-test
+          requires:
+            - build-push-image
+          filters:
+            branches:
+              only:
+                - staging
+
+  # Development environments
+  build-deploy-environment:
+    jobs:
+      - build-deploy-dev-env:
+          context: dev-test
+          filters:
+            branches:
+              only:
+                - /env-.*/
+
+  build-deploy-app:
     jobs:
       - test:
           context: dev-test
           filters:
             branches:
               ignore:
-                - /ephemeral.*/
+                - /env-.*/
+                - staging
       - build-push-image:
           context: dev-test
           filters:
             branches:
               only:
                 - master
-                - staging
       - deploy-image:
           context: dev-test
           requires:
@@ -176,7 +252,6 @@ workflows:
             branches:
               only:
                 - master
-                - staging
       - release:
           context: dev-test
           requires:
